--- 

- name: Install and set-up containerd 
  hosts: controlPlane:worker
  tasks:

    - name: Install containerd 
      ansible.builtin.dnf:
        name:
          - containerd.io
        state: present  

    - name: Generate containerd config 
      ansible.builtin.command:
        cmd: containerd config default > /etc/containerd/config.toml
        creates: /etc/containerd/config.toml

    - name: Enable systemd cgroups
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml 
        regexp: '^\s*SystemdCgroup\s*='
        line: '            SystemdCgroup = true' # 12 spaces!!!

    - name: Restart containerd 
      ansible.builtin.service:
        name: containerd
        state: restarted
        enabled: true