---

# --- vars (defined in group_vars/all/) ---
# ingress_nginx_version: "2.5.2"
#
# --- constants --- 
# chart: oci://ghcr.io/nginx/charts/nginx-ingress
# namespace: nginx-ingress 
# kind: DaemonSet
# service type: NodePort
# nodePort http: 30080
# nodePort https: 30443
# externalTrafficPolicy: local
# real-ip-recursive: true
# proxy-protocol: True
# server-tokens: false
# readOnlyRootFilesystem: True
# prometheus.create: true
#

- name: Install and set up NGINX Ingress Controller
  hosts: control_plane
  become: false
  tasks:

    - name: Install NGINX Ingress via Helm
      kubernetes.core.helm:
        name: nginx-ingress
        chart_ref: oci://ghcr.io/nginx/charts/nginx-ingress
        release_namespace: nginx-ingress
        create_namespace: true
        chart_version: "{{ ingress_nginx_version }}"
        wait: true
        values:
          controller:
            kind: daemonset
            readOnlyRootFilesystem: true
            service:
              type: NodePort
              externalTrafficPolicy: Local 
              httpPort:
                nodePort: 30080
              httpsPort:
                nodePort: 30443
            config:
              entries:
                proxy-protocol: "true"
                real-ip-header: "proxy_protocol"
                set-real-ip-from: "0.0.0.0/0"
                real-ip-recursive: "true"
                ssl-protocols: "TLSv1.2 TLSv1.3"
                hsts: "true"
                hsts-max-age: "31536000"
                server-tokens: "false"
          prometheus: 
            create: true

    - name: Wait for NGINX Ingress Controller deployment to be ready 
      kubernetes.core.k8s_info:
        kind: DaemonSet
        name: nginx-ingress-controller
        namespace: nginx-ingress 
      register: nginx_ds
      until:
        - nginx_ds.resources | length > 0
        - nginx_ds.resources[0].status.desiredNumberScheduled is defined
        - nginx_ds.resources[0].status.numberReady == nginx_ds.resources[0].status.desiredNumberScheduled
      retries: 60
      delay: 5