---

# --- vars (defines in group_vars/all.yml) ---
# pod_network_cidr: 10.244.0.0/16
# service_cidr: 10.96.0.0/12

# --- constants --- 
# control_plane_endpoint: private IP CP, dynamic fro, ansible_hosts
# cri_socket: unix:///run/containerd/containerd.sock
# cloud_provider: external 
# admin.conf: /etc/kubernetes/admin.conf
# kubeconfig: /home/ansible/.kube/config

- name: Init cluster
  hosts: control_plane
  tasks:

    - name: kubeadm init 
      ansible.builtin.command:
        cmd: >
          kubeadm init 
          --control-plane-endpoint={{ ansible_host }}
          --apiserver-advertise-address={{ ansible_host }}
          --pod-network-cidr={{ pod_network_cidr }}
          --service-cidr={{ service_cidr }}
          --cri-socket=unix:///run/containerd/containerd.sock
          --cloud-provider=external
        creates: /etc/kubernetes/admin.conf

- name: Set up kubectl for ansible user 
  hosts: control_plane
  tasks:

    - name: Create .kube dir
      ansible.builtin.file:
        path: /home/ansible/.kube
        state: directory
        mode: '0755'
        owner: ansible
        group: ansible

    - name: Copy admin.conf to kubeconfig 
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ansible/.kube/config
        remote_src: true
        owner: ansible
        group: ansible
        mode: '0600'

- name: Get join token
  hosts: control_plane
  tasks:

    - name: Generate token
      ansible.builtin.command:
        cmd: kubeadm token create --print-join-command
      register: kubeadm_join_command
      changed_when: false 

    - name: Set join command as a fact
      ansible.builtin.set_fact:
        join_command: "{{ kubeadm_join_command.stdout }}"

- name: Join worker nodes to cluster 
  hosts: workers
  tasks:

    - name: Join workers 
      ansible.builtin.command:
        cmd: "{{ hostvars[groups['control_plane'][0]]['join_command'] }}"
        creates: /etc/kubernetes/kubelet.conf