--- 

- name: Install and enable kubelet 
  hosts: controlPlane:worker
  tasks:

    - name: Install kubelet 
      ansible.builtin.dnf:
        name: "kubelet"
        state: present

    - name: Enable and start kubelet 
      ansible.builtin.service:
        name: kubelet
        enabled: true
        state: started 
