--- 

- name: Install kubeadm & kubectl 
  hosts: controlPlane:worker
  tasks:

    - name: Install kubeadm 
      ansible.builtin.dnf:
        name: "kubeadm"
        state: present 

    - name: Install kubectl 
      ansible.builtin.dnf:
        name: "kubectl"
        state: present 