--- 

- name: Install kubeadm & kubectl 
  hosts: controlPlane:worker
  tasks:

    - name: Install kubeadm 
      ansible.builtin.dnf:
        name: "kubeadm-{{ kubernetes_version  }}" # 1.35
        state: present 

    - name: Install kubectl 
      ansible.builtin.dnf:
        name: "kubectl-{{ kubernetes_version  }}"
        state: present 