ansible_become: true

# global

# versions

# Kubernetes
kubernetes_repo_version: "v1.35"
kubernetes_version: "1.35"
# Calico
calico_version: "v3.31.5"

# network
pod_network_cidr: "10.244.0.0/16"
service_cidr: "10.96.0.0/12"
